# Generated by Django 5.1.3 on 2024-11-14 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('C_SHARP', 'C#'), ('C_PLUS', 'C++'), ('PYTHON', 'Python'), ('JAVA', 'Java'), ('HTML_CSS', 'HTML/CSS'), ('DJANGO', 'Django'), ('REACT', 'React'), ('NODE', 'Node.js'), ('FLASK', 'Flask'), ('PANDAS', 'Pandas'), ('FRONT', 'Frontend-разработка'), ('BACK', 'Backend-разработка'), ('JS', 'JavaScript'), ('SQL', 'SQL'), ('MACHINE', 'Машинное обучение'), ('DATA', 'Анализ данных'), ('MATH', 'Теория вероятностей и мат. статистика'), ('ANDROID', 'Android'), ('IOS', 'IOS')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('difficulty_level', models.CharField(choices=[('FOR_BEGIN', 'Для начинающих'), ('FOR_INTER', 'Для уверенных'), ('FOR_PRO', 'Для профессионалов'), ('FOR_ALL', 'Для всех')], default='FOR_BEGIN', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('language', models.CharField(choices=[('RU', 'Русский'), ('EN', 'Английский'), ('ANY', 'Любой')], default='RU', max_length=20)),
                ('photo', models.ImageField(upload_to='photos/')),
                ('description', models.TextField()),
                ('tags', models.ManyToManyField(blank=True, related_name='courses', to='main.tag')),
            ],
        ),
    ]
