# Generated by Django 5.1.3 on 2024-11-14 13:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_tag_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=100, verbose_name='Название'),
            preserve_default=False,
        ),
    ]
