# Generated by Django 5.1.3 on 2024-11-26 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_course_title_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='isTeacher',
            field=models.BooleanField(default=False, verbose_name='Является преподавателем'),
        ),
    ]
