# Generated by Django 5.1.3 on 2024-12-04 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_module_options_module_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='created_courses',
            field=models.ManyToManyField(blank=True, related_name='creators', to='main.course'),
        ),
    ]
