# Generated by Django 5.1.3 on 2024-12-07 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_profile_created_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
